out.println("<!DOCTYPE html>");
out.println("<html lang=\"es\" class=\"no-js\">");
out.println("<head>");
		<!-- Mobile Specific Meta -->
out.println("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">");
		<!-- Favicon-->
out.println("<link rel="shortcut icon" href="../img/favicon.png">");
		<!-- Author Meta -->
out.println("<meta name=\"author\" content="\RosselTech\">");
		<!-- Meta Description -->
out.println("<meta name=\"description\" content=\"\">");
		<!-- Meta Keyword -->
out.println("<meta name=\"keywords\" content=\"\">");
		<!-- meta character set -->
out.println("<meta charset="UTF-8">");
		<!-- Site Title -->
out.println("<title>Upload Cafe</title>");
out.println("<link href=\"https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700\" rel=\"stylesheet\">"); 
			<!-- CSS ============================================= -->
out.println("<link rel=\"stylesheet\" href=\"css/linearicons.css\">");
out.println("<link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">");
out.println("<link rel=\"stylesheet\" href=\"css/bootstrap.css\">");
out.println("<link rel=\"stylesheet\" href=\"css/magnific-popup.css\">");
out.println("<link rel=\"stylesheet\" href=\"css/animate.min.css\">");
out.println("<link rel=\"stylesheet\" href=\"css/owl.carousel.css\">");
out.println("<link rel=\"stylesheet\" href=\"css/main.css\">");
out.println("</head>");
out.println("<body>");
			
out.println("<section class=\"banner-area\" id=\"home\">");
				<!-- Start Header Area -->
out.println("<header class=\"default-header\">");
out.println("<nav class=\"navbar navbar-expand-lg  navbar-light\">");
out.println("<div class=\"container\">");
out.println("<a class=\"navbar-brand\" href=\"index.html\">");
out.println("<img src=\"img/logoQR.png\" alt=\"\">");
							    <!-- <button class="primary-btn mt-20">RosselTech<span class="lnr lnr-arrow-right"></span></button> -->
out.println("</a>");
out.println("<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">");
out.println("<span class=\"text-white lnr lnr-menu\"></span>");
out.println("</button>");

out.println("<div class=\"collapse navbar-collapse justify-content-end align-items-center\" id=\"navbarSupportedContent\">");
out.println("<ul class=\"navbar-nav\">");
out.println("<li><a href=\"../index.html\">Inicio</a></li>");
out.println("<li><a href=\"#about\">Somos</a></li>");									
out.println("<li><a href=\"#secvice\">Servicios</a></li>");
out.println("<li><a href=\"#gallery\">Galeria</a></li>");
out.println("<li><a href=\"#faq\">FaQ</a></li>");
out.println("<li><a href=\"#contact\">Contacto</a></li>");
									<!-- Dropdown -->
out.println("<li class=\"dropdown\">");
out.println("<a class=\"dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\">Otras P&aacute;ginas</a>");
out.println("<div class=\"dropdown-menu\">");
out.println("<a class=\"dropdown-item\" href=\"#\">Generador QR</a>");
out.println("<a class=\"dropdown-item\" href=\"../elements.html\">Elementos</a>");
out.println("</div></li></ul></div></div></nav></header></section>");
				<!-- End Header Area -->				
			
			<!-- start contact Area -->	
			<!-- out.println("<%@ include file='../inc/encRosselTech.inc' %>"); -->