		<div align=center style="HEIGHT: 10px">
			<div align=center style="HEIGHT: 15px">
				<hr color="#E0F2F7" size="4">	
			</div>
		</div>
	
		<div id="tipDay" align=right>
			<font face=sans-serif size =1 color=#0B3861>
				Control de Gestion: &nbsp;&nbsp;
			</font>
			<font face=sans-serif size =1 color=#FF0000>
				©2014 
			</font>
			<font face=sans-serif size =1 color=#0B3861>
				ORG R.Co Software Factory &nbsp;&nbsp;
			</font>
		</div>